FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod ./
# COPY go.sum ./ # Uncomment when dependencies are added
# RUN go mod download

COPY . .

RUN go build -o worker cmd/worker/main.go

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/worker .

CMD ["./worker"]
